### PR TITLE
fixes bug #23 - with wrong routes for unauthenticated multinenancy users

### PR DESCRIPTION
**Pull request by OccTherapist**
- **fixes bug #23 - with wrong routes for unauthenticated multinenancy users**

### CODE REVIEW

**Comment by OccTherapist** [comment]
@JibayMcs do you have any concerns about this commit? Should I fix something?

**Comment by Mrkbingham** [comment]
Would love to see this one go into a release soon! @JibayMcs

**Comment by jeffegiovani** [comment]
I have a similar error in multitenant application, see:
image

**Comment by JibayMcs** [comment]
Oh god ! Didn't see the notification !
Thanks for you PR ! :heart:  :pray: 

Now released ! https://github.com/JibayMcs/filament-tour/releases/tag/v3.1.1

Many many thanks ! :heart:

**Pull request merged**
